### ISSUE TITLE
CSS中的position属性

### ISSUE THREAD

**Issue by Lynn0108** [Lynn0108/blog#15]
|值      |描述|
|:------- |:----|
|static   |默认值，元素出现在正常的流中（忽略 top, bottom, left, right 或者 z-index 声明）。|
|absolute |绝对定位，元素脱离文档流，相对于非static定位的第一个父元素进行定位。元素的位置通过 "left", "top", "right" 以及 "bottom" 属性进行规定。|
|fixed    |绝对定位，元素脱离文档流，相对于浏览器窗口进行定位。元素的位置通过 "left", "top", "right" 以及 "bottom" 属性进行规定。|
|relative|生成相对定位的元素，相对于其正常位置进行定位。|
|inherit|规定应该从父元素继承 position 属性的值。|

_来源：W3School_

## `position: relative`
1. 初始位置：

![image](https://github.com/Lynn0108/demoForBlog/raw/master/note-img/position0814_1.png)

2. 相对于谁定位

```css
#green {
    position: relative;
    top: 40px;
    left: 40px;
}
```
![image](https://github.com/Lynn0108/demoForBlog/raw/master/note-img/position0814_2.png)

其中红边框代表绿色框的原位置，绿色框**相对于自己原来在文档流中的位置**偏移了，但是原来的位置还是被占据着（**不脱离文档流**）。

### 脱离文档流
还是上面的例子，把position的值改为absolute，会发生什么？
![image](https://github.com/Lynn0108/demoForBlog/raw/master/note-img/position0814_3.jpg)

其中红边框表示紫色框的原位置，紫色框占据了绿色框的位置，因为绿色框脱离了文档流，把位置“让”了出来。

### 位置值
在上文中，设置了第一个框绝对定位，如果我们设置第二个框绝对定位呢？

我们会神奇的发现，它还在它原来的位置上“乖乖”待着。绝对定位失效了吗？元素并没有脱离文档流？

并不是。我们可以在第二个div后加上一行文字，发现文字是紧跟着绿色框的位置出现的。
![image](https://github.com/Lynn0108/demoForBlog/raw/master/note-img/position0814_5.jpg)

紫色框之所以乖乖的呆在原位置，是我们没有设置top、bottom、left、right值，它们被设置成了默认值。

在这四个值中也是要“论资排辈”的：如果都进行了设置则以top和left值为优先。

### TIP: 绝对定位元素的居中

如果设置了left和right都为0（或者其他相同的数值），再设置`margin: auto`，轻松实现了水平居中。同理，设置top和bottom也可以实现垂直居中。
![image](https://github.com/Lynn0108/demoForBlog/raw/master/note-img/position0814_6.jpg)

### 相对谁定位
相对于非static定位的第一个父元素进行定位。

**但这里要注意一点**：relative在最外层时是相对`<body>`标签边界定位的，而absoulte在无非static定位父级时是相对`<html>`标签边界定位的。具体看下图

![image](https://github.com/Lynn0108/demoForBlog/raw/master/note-img/position0814_4.png)
```css
#green {
    position: relative;
    left: 200px
}
#purple {
    position: absolute;
    top: 0;
}
```
其中，紫色边框为`<html>`，绿色边框为`<body>`

### 如果父元素有边距和边框？
```css
#wrap {
    position: relative;
    width: 400px;
    height: 400px;
    border: 4px solid #FAC;
    margin: 40px;
    padding: 20px;
}
#green {
    position: absolute;
    top: 0;
    left: 0;
}
```
![image](https://github.com/Lynn0108/demoForBlog/raw/master/note-img/position0814_7.jpg)

从结果中看出，绝对定位是相对于父元素的**边框内部**定位的。

### 相对谁定位
fixed相对于浏览器窗口进行偏移定位，它的位置不跟随滚动条的滚动而发生变化

### 一个小问题
在手机端使用固定定位时，如果元素不是body的直接子元素，在ios端会fixed会失效。
