### ISSUE TITLE
图片尺寸未知且大于容器尺寸时的居中问题

### ISSUE THREAD

**Issue by Lynn0108** [Lynn0108/blog#2]
图片尺寸超出容器尺寸时，`text-align: center`、`margin: 0 auto`以及`margin: auto`等方法都会失效，可以使用以下**纯CSS**方法。（其中css均使用less进行编译）
``` html
<div id="test">
    <img src="IMGSRC" />
</div>
```
### CSS3动画
``` css
#test {
     width: 300px;
     height: 300px;
     overflow: hidden;
     position: relative;
     img {
          position: absolute;
          left: 50%;
          top: 50%;
          transform: translate(-50%, -50%);
     }
}
```
### `display: flex`
```css
#test {
     width: 300px;
     height: 300px;
     overflow: hidden;
     display: flex;
     justify-content: center;
     align-items: center;
}
```
### 用作背景图片
```html
<div id="test"></div>
```
```css
#test {
     width: 300px;
     height: 300px;
     overflow: hidden;
     background-image: url('IMGSRC');
     background-position: center;
     background-repeat: no-repeat;
}
```
前三个方法由于使用了CSS3，可能会存在一些兼容性的问题
### 为图片套一个块级元素，使相对于容器偏移50%，再使图片相对于它反向偏移50%，`#hide`用于将div撑到和img一样宽高
```html
<div id="test">
     <div>
          <img src="IMGSRC" id="hide" />
          <img src="IMGSRC" />
      </div>
</div>
```
```css
#test {
     width: 300px;
     height: 300px;
     overflow: hidden;
     position: relative;
     div {
          position: absolute;
          left: 50%;
          top: 50%;
          img {
               position: absolute;
               left: -50%;
               top: -50%;
          }
          #hide {
               visibility: hidden;
               position: static;
          }
     }
}
```
[demo源码--Github](https://github.com/Lynn0108/demoForBlog/tree/master/demo0628)
![image](https://github.com/Lynn0108/demoForBlog/raw/master/demo0628/css0628_1.gif)
[图片来源](http://old.zcool.com.cn/u/13251201)
[参考：图片溢出居中](http://nec.netease.com/library/141122)

_有不足之处还请指正，转载请注明出处。谢谢。_
